
# Read the csv file generated by python 
DataDf <- read.csv('df.csv', header=TRUE)

install.packages('rworldmap')
library(rworldmap)


par(mai=c(0,0,0.2,0),xaxs="i",yaxs="i") 
#align the country code with the country column in the csv file

sPDF <- joinCountryData2Map( DataDf,
                             joinCode = "NAME",
                             nameJoinColumn = "Country")
#mapCountryData( sPDF, nameColumnToPlot="Access_to_Electricity" )

#creating a user defined colour palette 
op <- palette(c('green','yellow','orange','red')) 
#find quartile breaks 
cutVector <- quantile(sPDF@data[["Access_to_Electricity"]],na.rm=TRUE) 
#classify the data to a factor 

# Access to electricity Mapping
sPDF@data[["Access_to_Electricity"]] <- cut(sPDF@data[["Access_to_Electricity"]], cutVector, include.lowest=TRUE ) 
#rename the categories 
levels(sPDF@data[["Access_to_Electricity"]]) <- c('low', 'med', 'high', 'vhigh') 
#mapping
mapCountryData(sPDF, nameColumnToPlot= "Access_to_Electricity",catMethod="categorical", mapTitle="Access to Electricity Categories", colourPalette="palette", oceanCol="lightblue", missingCountryCol="white")

#GDP Mapping
cutVector <- quantile(sPDF@data[["GDP"]],na.rm=TRUE) 
#classify the data to a factor 

sPDF@data[["GDP"]] <- cut(sPDF@data[["GDP"]], cutVector, include.lowest=TRUE ) 
#rename the categories 
levels(sPDF@data[["GDP"]]) <- c('low', 'med', 'high', 'vhigh') 
#mapping
mapCountryData(sPDF, nameColumnToPlot= "GDP",catMethod="categorical", mapTitle="GDP Categories", colourPalette="palette", oceanCol="lightblue", missingCountryCol="white")


#Energy_per_GDPunit Mapping
cutVector <- quantile(sPDF@data[["Energy_per_GDPunit"]],na.rm=TRUE) 
#classify the data to a factor 

sPDF@data[["Energy_per_GDPunit"]] <- cut(sPDF@data[["Energy_per_GDPunit"]], cutVector, include.lowest=TRUE ) 
#rename the categories 
levels(sPDF@data[["Energy_per_GDPunit"]]) <- c('low', 'med', 'high', 'vhigh') 
#mapping
mapCountryData(sPDF, nameColumnToPlot= "Energy_per_GDPunit",catMethod="categorical", mapTitle="Energy_per_GDPunit Categories", colourPalette="palette", oceanCol="lightblue", missingCountryCol="white")

